name: cellechua
favicon: null
layout_spectrum: 0.3766431414987892
typography_spectrum: 0.28792377980425954
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c0fdfe'
    - '#64a7b8'
    - '#0d0d0d'
    - '#7f472e'
    - '#0d6c72'
  brandStrength: 0.23229459929279983
  lightness: 0.6157925114966929
  saturation: 0.2801618983503431
  rhythmicContrast: 0.37762804329395294
purpose: []
